hooks:
  after:release:
    - echo Successfully released ${name} v${version} to ${repo.repository}.
git:
  changelog: git log --pretty=format:"* %s (%h)" ${latestTag}...HEAD
  requireBranch: main
  requireCleanWorkingDir: true
  requireUpstream: false
  commit: true
  commitMessage: "[skip ci] Release v${version}"
  tag: true
  push: true
plugins:
  "@release-it/conventional-changelog":
    infile: CHANGELOG.md
    preset:
      name: conventionalcommits
      types:
        - type: build
          section: Build Changes
        - type: ci
          section: CI Changes
        - type: docs
          section: Doc Updates
        - type: feat
          section: Features
        - type: fix
          section: Fixes