language: python

branches:
  only:
  - main

env:
  - NODE_VERSION="12"

before_install:
  - env
  - nvm install $NODE_VERSION

install:
  - ./install_prereqs.sh

script:
  - git remote rm origin
  - git remote add origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git symbolic-ref HEAD "refs/heads/${TRAVIS_BRANCH}"
  - release-it